PARAMETERS = {
    'spring': {
        'Пастернак': {
            'purchase_price': 20,
            'growth_time': 6,
            'Prod1':35,
            'Prod2':43,
            'Prod3':52,
            'Prod4':70,
            'crop_kilkist': 1,
            'k_posadku': 6,
            'index_bochonok': 2.25,
        },
        'картопля': {
            'purchase_price': 50,
            'growth_time': 4,
            'Prod1': 80, 
            'Prod2': 100, 
            'Prod3': 120, 
            'Prod4': 160, 
            'crop_kilkist': 1.2,
            'k_posadku': 4,
            'index_bochonok': 2.25,
        },
        'Кудрява капуста': {
            'purchase_price': 70,
            'growth_time': 4,
            'Prod1': 110, 
            'Prod2': 137, 
            'Prod3': 165, 
            'Prod4': 220,
            'crop_kilkist': 1,
            'k_posadku': 4,
            'index_bochonok': 2.25,
        },
        'Рис': {
            'purchase_price': 40,
            'growth_time': 3,
            'Prod1': 30, 
            'Prod2': 37, 
            'Prod3': 45, 
            'Prod4': 60,
            'crop_kilkist': 1,
            'k_posadku': 3,
            'index_bochonok': 2.25,
        },
        'Цвітна капуста': {
            'purchase_price': 80,
            'growth_time': 2,
            'Prod1': 175, 
            'Prod2': 218, 
            'Prod3': 262, 
            'Prod4': 350,
            'crop_kilkist': 1,
            'k_posadku': 2,
            'index_bochonok': 2.25,
        },
        'Часник': {
            'purchase_price': 40,
            'growth_time': 4,
            'Prod1': 60, 
            'Prod2': 75, 
            'Prod3': 90, 
            'Prod4': 120,
            'crop_kilkist': 1,
            'k_posadku': 4,
            'index_bochonok': 2.25,
        },
        'Кавове зерно': {
            'purchase_price': 2500,
            'growth_time': 9,
            'Prod1': 15, 
            'Prod2': 18, 
            'Prod3': 22, 
            'Prod4': 30,
            'crop_kilkist': 4,
            'k_posadku': 1,
            'index_bochonok': 0,
        },
        'Зелена фасоль': {
            'purchase_price': 2500,
            'growth_time': 9,
            'Prod1': 15, 
            'Prod2': 18, 
            'Prod3': 22, 
            'Prod4': 30,
            'crop_kilkist': 4,
            'k_posadku': 1,
            'index_bochonok': 2.25,
        },
        'Клубніка': {
            'purchase_price': 100,
            'growth_time': 5,
            'Prod1': 120, 
            'Prod2': 150, 
            'Prod3': 180, 
            'Prod4': 240,
            'crop_kilkist': 4,
            'k_posadku': 1,
            'index_bochonok': 3,
        },
    },
    'summer': {
        'Диня': {
            'purchase_price': 80,
            'growth_time': 2,
            'Prod1': 250, 
            'Prod2': 312, 
            'Prod3': 375, 
            'Prod4': 500,
            'crop_kilkist': 1,
            'k_posadku': 2,
            'index_bochonok': 3,
        },
        'Пекучий перець': {
            'purchase_price': 40,
            'growth_time': 8,
            'Prod1': 40,
            'Prod2': 50, 
            'Prod3': 60, 
            'Prod4': 80,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 2.25,
        },
        'Карамбола': {
            'purchase_price': 400,
            'growth_time': 2,
            'Prod1': 750,
            'Prod2': 937, 
            'Prod3': 1125, 
            'Prod4': 1500,
            'crop_kilkist': 1,
            'k_posadku': 2,
            'index_bochonok': 3,
        },
        'Червона капуста': {
            'purchase_price': 100,
            'growth_time': 3,
            'Prod1': 260,
            'Prod2': 325, 
            'Prod3': 390, 
            'Prod4': 520,
            'crop_kilkist': 1,
            'k_posadku': 3,
            'index_bochonok': 2.25,
        },
        'Кукурудза': {
            'purchase_price': 150,
            'growth_time': 4,
            'Prod1': 50,
            'Prod2': 62, 
            'Prod3': 75, 
            'Prod4': 100,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 2.25,
        },
        'Помдор': {
            'purchase_price': 50,
            'growth_time': 5,
            'Prod1': 60,
            'Prod2': 75, 
            'Prod3': 90, 
            'Prod4': 120,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 2.25,
        },
        'Пшениця': {
            'purchase_price': 10,
            'growth_time': 6,
            'Prod1': 25,
            'Prod2': 31, 
            'Prod3': 37, 
            'Prod4': 50,
            'crop_kilkist': 1,
            'k_posadku': 6,
            'index_bochonok': 8,
        },
        'Редиска': {
            'purchase_price': 40,
            'growth_time': 4,
            'Prod1': 90,
            'Prod2': 112, 
            'Prod3': 135, 
            'Prod4': 180,
            'crop_kilkist': 1,
            'k_posadku': 4,
            'index_bochonok': 2.25,
        },
        'Хміль': {
            'purchase_price': 60,
            'growth_time': 17,
            'Prod1': 25,
            'Prod2': 31, 
            'Prod3': 37, 
            'Prod4': 50,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 12,
        },
        'Чорниця': {
            'purchase_price': 80,
            'growth_time': 4,
            'Prod1': 50,
            'Prod2': 62, 
            'Prod3': 75, 
            'Prod4': 100,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 3,
        },
    },
    'autumn': {
        'Амарант': {
            'purchase_price': 80,
            'growth_time': 3,
            'Prod1': 150,
            'Prod2': 187, 
            'Prod3': 225, 
            'Prod4': 300,
            'crop_kilkist': 1,
            'k_posadku': 3,
            'index_bochonok': 2.25,
        },
        'Артишок': {
            'purchase_price': 30,
            'growth_time': 3,
            'Prod1': 160,
            'Prod2': 200, 
            'Prod3': 240, 
            'Prod4': 320,
            'crop_kilkist': 1,
            'k_posadku': 3,
            'index_bochonok': 2.25,
        },
        'Баклажан': {
            'purchase_price': 20,
            'growth_time': 5,
            'Prod1': 60,
            'Prod2': 75, 
            'Prod3': 90, 
            'Prod4': 120,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 2.25,
        },
        'Батат': {
            'purchase_price': 60,
            'growth_time': 2,
            'Prod1': 160,
            'Prod2': 200, 
            'Prod3': 240, 
            'Prod4': 320,
            'crop_kilkist': 1,
            'k_posadku': 3,
            'index_bochonok': 2.25,
        },
        'Бок-чой': {
            'purchase_price': 50,
            'growth_time': 6,
            'Prod1': 80,
            'Prod2': 100, 
            'Prod3': 120, 
            'Prod4': 160,
            'crop_kilkist': 1,
            'k_posadku': 6,
            'index_bochonok': 2.25,
        },
        'Виноград': {
            'purchase_price': 60,
            'growth_time': 6,
            'Prod1': 80,
            'Prod2': 100, 
            'Prod3': 120, 
            'Prod4': 160,
            'crop_kilkist': 1,
            'k_posadku': 1,
            'index_bochonok': 3,
        },
        'Клюква': {
            'purchase_price': 240,
            'growth_time': 5,
            'Prod1': 75,
            'Prod2': 93, 
            'Prod3': 112, 
            'Prod4': 150,
            'crop_kilkist': 2,
            'k_posadku': 1,
            'index_bochonok': 3,
        },
        'Буряк': {
            'purchase_price': 20,
            'growth_time': 4,
            'Prod1': 100,
            'Prod2': 125, 
            'Prod3': 150, 
            'Prod4': 200,
            'crop_kilkist': 1,
            'k_posadku': 4,
            'index_bochonok': 2.25,
        },
        'Гарбуз': {
            'purchase_price': 100,
            'growth_time': 2,
            'Prod1': 320,
            'Prod2': 400, 
            'Prod3': 480, 
            'Prod4': 640,
            'crop_kilkist': 1,
            'k_posadku': 2,
            'index_bochonok': 2.25,
        },

    },
    'winter': {
        'А тут нічого)))': {
            'purchase_price': 100,
            'growth_time': 2,
            'Prod1': 320,
            'Prod2': 400, 
            'Prod3': 480, 
            'Prod4': 640,
            'crop_kilkist': 1,
            'k_posadku': 2,
        },
    },
}